/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sebastian' at '12/6/15 12:30 AM' with Gradle 2.9
 *
 * @author Sebastian, @date 12/6/15 12:30 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
